//LeStratBot main script here
//Authors: Mulligan and Bambakidis
//For now just pseudocode/general idea of specific rules for bot to follow.

//4-6min Scalp capabilities integration with at minumum cipher B
//  -MoneyFlowIndex is our primary weighted indicator
//  -Momentum apexs are trigger events
//  -RSI position (0-100) is more influencial and telsome than stochastic 
//      -RSI 80 Is overbought, 20 is oversold.  Crossing the 50 threshold is considered a trend. color least regarded and based on "signal strength".
//potential confluence integration with le 15min - 4Hour 
//focus on Cipher B and DBSI indicators, RSI and A, and potentially SR are for future confluence factors.
//Future potential confluence with totality cipher awarness.